export const SUCCESS = "SUCCESS";
export const ERROR= "ERROR";

export const ERR_VALIDATION = "ERR_VALIDATION";
export const ERR_MYSQL = "ERR_MYSQL";
export const ERR_REDIS = "ERR_REDIS";

export const ERR_DATA_NOT_FOUND = "ERR_DATA_NOT_FOUND";
export const ERR_DATA_EXISTS = "ERR_DATA_EXISTS";

export const ERR_TOKEN_NOT_FOUND = "ERR_TOKEN_NOT_FOUND";

export const ERR_STATUS_INACTIVE = "ERR_STATUS_INACTIVE";
export const ERR_PERMISSION_REQUIRED = "ERR_PERMISSION_REQUIRED";

export const ERR_FILE_TYPE_UNKNOWN = "ERR_FILE_TYPE_UNKNOWN";
export const ERR_PRODUCT_IMAGE_EXISTS = "ERR_PRODUCT_IMAGE_EXISTS";